---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: topic-example
  namespace: kafka
spec:
  replicas: 1
  partitionCount: 1
  kafkaRestClassRef:
    name: kafka-rest
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: manual-topic
  namespace: kafka
spec:
  replicas: 1
  partitionCount: 1
  kafkaRestClassRef:
    name: kafka-rest
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: demo
  namespace: kafka
spec:
  replicas: 1
  partitionCount: 1
  kafkaRestClassRef:
    name: kafka-rest
